# from https://hub.docker.com/r/shinsenter/statamic
# inherits from https://hub.docker.com/r/shinsenter/php
# if volume folder is empty, it installs statamic there alongside deps
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_URL=https://localhost
    ports:
      - '443:443'
    volumes:
      # Application
      - ./statamic:/var/www/html
      # Dev SSL keys (npm run devcerts in /statamic)
      - ./localhost.crt:/etc/ssl/site/server.crt:ro
      - ./localhost.key:/etc/ssl/site/server.key:ro
